### ISSUE TITLE
Missing directory 'cache'

### ISSUE THREAD

**Issue by KloonDuino** [PrestaShop/community-theme-16#11]
There is a missing directory in the theme dir.
There should be a 'cache' directory in the root of the theme. Else the cache will not work and you get an error in the BO.

**Comment by gskema** [comment]
Hello,

`cache` folder gets added during build process, which has to be done by the developer:

https://github.com/PrestaShop/community-theme-16/blob/master/gulpfile.js#L12-L14

Theme archive wthl all required folders will be under **Releases** section. First release (0.1.0) is coming soon.

**Comment by KloonDuino** [comment]
Nowhere to be found.....

![presta1](https://cloud.githubusercontent.com/assets/8421220/12025263/2b418918-adad-11e5-813c-9414a55f6fac.jpg)

**Comment by gskema** [comment]
Hello,

please trying downloading [v0.1.0-community-theme-16.zip](https://github.com/PrestaShop/community-theme-16/releases/download/v0.1.0/v0.1.0-community-theme-16.zip) from

https://github.com/PrestaShop/community-theme-16/releases
