### ISSUE TITLE
Touch detection

### ISSUE THREAD

**Issue by gskema** [PrestaShop/community-theme-16#14]
Touch (possible) devices should be detected on load and body class `.has-touch` added

**Comment by kpodemski** [comment]
Is it possible? I remember that it was very tricky and easier was to check if we're on mobile

**Comment by gskema** [comment]
Hi,

we need to consider this at least. having touch classes would enable designers to show full element info for touch devices instead of having to `hover` over them.

Detecting touch is hard yes, but we can use combination of methods: API detection + user string matching. I heard it's fairly effective. It would be good when the touch styles don't differ much from default styles.
