### ISSUE TITLE
Theme name shouldn't be hardcoded

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/community-theme-16#160]
I think `community-theme16` shouldn't be harcoded in gulp and everywhere else, if someone wants to start work from scratch using this repo it will be nice to just change constant in js to work on different theme name, what you think @gskema ?

**Comment by gskema** [comment]
Sure, it shouldn't be hardcoded. Not a big priority right now

**Comment by kpodemski** [comment]
Done in #171
