### ISSUE TITLE
Do we really need Compass?

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/community-theme-16#173]
I noticed that there is almost none using of Compass in project, isn't is better to simply extend Bootstrap mixins and avoid using of Compass? It will allow users use third-party compilers like Prepros or Koala which is not possible right now.

**Comment by gskema** [comment]
Sure, that would be great. Can you tell sow us how it would work (compiling all project .scss files)? I only know how to compile one file without compass :D

**Comment by gskema** [comment]
I like compass because it fixed this problem:
https://github.com/PrestaShop/community-theme-16/blob/dev/themes/community-theme-16/config.rb#L31
