### ISSUE TITLE
Checkboxes, radio buttons

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/community-theme-16#174]
Hi @gskema 

I noticed this problem:
![image](https://cloud.githubusercontent.com/assets/2137763/14293195/c7a71afa-fb6b-11e5-8991-1ff41bc25686.png)

caused because `position: absolute;` here:
`sass/vendor/bootstrap/bootstrap/_forms.scss`

could you reproduce this error?

**Comment by gskema** [comment]
Hmm, not really. What browser are you running?

You should check if the problem occurs in the default Bootstrap too:
http://getbootstrap.com/css/#forms-example

**Comment by kpodemski** [comment]
Ahhh, I see, for some reason I have loaded uniform.default.css o_O

**Comment by kpodemski** [comment]
I must made some mistake while starting a project

**Comment by kpodemski** [comment]
Ok, I've had previously builded package and `/themes/community-theme` and files were mixed up, old ones with new ones
