### ISSUE TITLE
Help moving cttopmenu to different location

### ISSUE THREAD

**Issue by giles247** [PrestaShop/community-theme-16#208]
I've added a new hook to cttopmenu module as I don't want it to display in hookTop. So in my header.tpl I now have:

`<div id="header-menu">
    <div class="container">
      <div class="row">
        {hook h='displayHeaderMenu'}
    </div>
  </div>
`

The menu is being generated correctly in new area i.e. items tree built, but it is not being styled correctly. This is possibly because the code in fo.js is not finding the menu, but I cannot see anything that the module code that ties this menu to it's original location under header-blocks.

Can anyone help me?

**Comment by gskema** [comment]
`fo.js` mostly contain code making the menu work as 'hover' menu (doesn't work very well atm).
`fo.css` is namespaced to `#cttopmenu`, so I have no idea why it wouldn't be working.

Did you copy these lines to your new hook:

```
$this->context->controller->addCSS($this->_path.'views/css/fo.css');
$this->context->controller->addJS($this->_path.'views/js/fo.js');
```

Also, have you cleared the cache?

**Comment by giles247** [comment]
Thanks for reply. You are correct in that those two resources are not being loaded. But I don't understand why. My hookDisplayHeaderMenu function is clone of hookDisplayTop. Note: Is your function hookDisplayHeader supposed to have commented out lines?

**Comment by giles247** [comment]
Ok, so If I add those lines to your existing hookDisplayHeader it works. So I guess I'm missing something as to why those resources not being loaded in my hookDisplayHeaderMenu but do get loaded in your hookDisplayTop. Hmmm

**Comment by gskema** [comment]
It is possible that when you custom hooks is being executed, it is too late to change the header, perhaps your hooks is part of the last compilation process (the content template)?

**Comment by gskema** [comment]
If you're having issues working with he theme, you should come and ask questions at https://gitter.im/PrestaShop/community-theme-16

**Comment by kpodemski** [comment]
Hi @redactuk 

I suggest you to check latest improvements in `cttopmenu`, you should download package and update module, after that you'll have possibility to place menu wherever you want using custom hook: `{hook h='displayCtTopMenu'}`

**Comment by giles247** [comment]
New change works perfectly. Many thanks.
