### ISSUE TITLE
cttopmenu theme styling

### ISSUE THREAD

**Issue by giles247** [PrestaShop/community-theme-16#216]
Does cttopmenu currently support theme style overrides? I've not yet upgraded to 0.11.0 but in v0.10.0 my customised sass/modules/cttopmenu/fo.scss correctly compiles to mytheme/modules/cttopmenu/fo.css, but this stylesheet is not being picked i.e. default module one is till being read.

**Comment by kpodemski** [comment]
Your CSS should be in `mytheme/css/modules/cttopmenu/`. Sometimes you need to move CSS files to `mytheme/css/modules/cttopmenu/css`.

**Comment by giles247** [comment]
Thanks, but that doesn't seem to work. The module's native stylesheet is still being loaded.

**Comment by kpodemski** [comment]
Latest version of `cttopmenu` where styles are added into `displayHeader` hook?

**Comment by giles247** [comment]
Ok, solved. Needs to be in /views/css/. Wish there was some consistency with this in PS.

**Comment by kpodemski** [comment]
Agree on that :(

**Comment by giles247** [comment]
One further comment in case useful to anyone later: if you want to keep a sass file for this module in your theme rather than updating the module one then you will need to add it to yourtheme/sass/modules/cttopmenu/views/css Not bery logical, but doing it that way compile-css will then place the compiled css file in the correct subfolders i.e. views/css.
