### ISSUE TITLE
Sass not being compiled in 0.11.0

### ISSUE THREAD

**Issue by giles247** [PrestaShop/community-theme-16#217]
Updated to latest version with clean install. Using method suggested to dump repository on top of local test version of prestashop. gulp commands go through the motions with no errors but sass style changes are just not being compiled. Anyone else had any issues?

**Comment by kpodemski** [comment]
Do you have any errors in CLI after running `gulp compile-css`?

**Comment by giles247** [comment]
No errors

**Comment by kpodemski** [comment]
Weird, I just tested it and everything seems ok:
1. downloaded package
2. `npm install`
3. `gulp compile-css`

And everything working correctly. Did you have notification about successfuly compiled CSS?

@gskema any ideas?

**Comment by giles247** [comment]
Noticed in code running compile-css should give success notification - it does not. Yet the compile-module-css does give that notification

**Comment by kpodemski** [comment]
What OS?

Let's wait for @gskema as I don't have any ideas for now and didn't have any issues at all after moving to Bourbon and LibSass

**Comment by giles247** [comment]
ok, problem solved. Even though I thought it was a clean install I had still made one change - to include a new _partial in global.css yet not actually add the corresponding file. In this situation sass just bombs out with no error message  - hence it didn't complete compile-css. Apologies for wasting your time on this one - schooloy error on my part.

**Comment by gskema** [comment]
Most likely it's related to this: https://github.com/PrestaShop/community-theme-16/commit/d5431da91ad6da492f00a6cde8a2c98bb5a21622.

**Comment by kpodemski** [comment]
@gskema if so let's release 0.11.1 or 0.12 today or tomorrow as this is critical
