### ISSUE TITLE
cttopmenu dropdown on mouse hover option issue

### ISSUE THREAD

**Issue by giles247** [PrestaShop/community-theme-16#219]
When the module option 'Open menu item dropdown on mouse hover' is selected, when the menu is then displayed in mobile view opening any submenu then automatically opens parent group link i.e. you can't open subgroup and leave it displayed. Hope that makes sense!

**Comment by gskema** [comment]
Sorry to say that 'on hover' option doesn't work very well. Bootstrap's dropdown doesn't support hover events, it's something we tried to implement ourselves. Currently, the best option is to use 'on click' menu type or use a another library to build a menu.

I was hoping that someone could suggest how to implement 'on hover' menu.

**Comment by kpodemski** [comment]
I'll work on this later today

**Comment by giles247** [comment]
Yes I prefer to use 'on click' as hover not an option on mobile devices. I'm guessing a possible solution would be that 'Open menu item dropdown on mouse hover' is only supported for larger screen sizes.

**Comment by gskema** [comment]
It used to work fairly well on mobile version too (collapsed menu) - all the hover handlers were disabled in collapsed view. I've tested it now and it didn't work :(

**Comment by gskema** [comment]
#227
