### ISSUE TITLE
cttopmenu category list option

### ISSUE THREAD

**Issue by giles247** [PrestaShop/community-theme-16#220]
Would it be possible in the future to add a 'Category List' option to the list of menu Item Types? i.e. just a list of all categories like the Manufactuer and Suppliers list options.

**Comment by gskema** [comment]
Well technically you should be able to add 'category tree', where top level category is root category (id:2). Have you tried that?

**Comment by giles247** [comment]
Yes I can do that, but what I'm after is flat list in alphabetical order i.e. not displayed as hierarchy

**Comment by gskema** [comment]
Hello, have this solved this issue? I think the best option would be to customize the module, add a custom menu item builder function and a new menu item type. I would like to close this.

**Comment by giles247** [comment]
This was a request for change to add the functionality I proposed - something I think others would also find useful. I don't see how I can solve this without modifying or cloning your module.

**Comment by gskema** [comment]
We'll discuss this adding feature. About modifying the module: theme was built specifically to be modified and extended, so by the same logic so should be the theme modules.

**Comment by gskema** [comment]
https://github.com/PrestaShop/community-theme-16/pull/233

What do you think?
