### ISSUE TITLE
possibility to save full html in the copyright field of ctconfiguration module

### ISSUE THREAD

**Issue by kimlop** [PrestaShop/community-theme-16#221]
Hi, 
it's possible to implement the save of full html in the copyright field of ctconfiguration module?

**Comment by gskema** [comment]
Hello,

I believe that it is possible to use HTML, since the hint for this field is "HTML is allowed. Enter &amp;copy; for copyright symbol." You should try.

However, rich text editor is not available for this fields yet.

**Comment by kimlop** [comment]
yes I knot that is possible to use html symbols, but not tags. I don't need a rich text editor, but only the possibility to use tag to include an image.
And before open a new issue I tried to do some experiments...
