### ISSUE TITLE
Prestashop 1.6.1.9 baseAdminDir

### ISSUE THREAD

**Issue by infinite-system** [PrestaShop/community-theme-16#262]
Just downloaded and installed prestashop 1.6.1.9 and in the admin area,
uploading logo didn't work. 

Opened dev console and it said 
baseAdminDir is undefined in notifications.js

so i had to manually add

var baseAdminDir = '/admin{randomvalueofmy admin area}/';

and then it worked, so it's a bug and should be there by default.

**Comment by gskema** [comment]
Hello,

is this issue related to theme?

**Comment by wucherpfennig** [comment]
still open in 1.6.11 / default theme

**Comment by kpodemski** [comment]
@wucherpfennig you can report this issue on forge.prestashop.com, it's not related to community theme

**Comment by volga** [comment]
@wucherpfennig, @masterm1nd, clean the browser cache after your installation. This error occurs because the file in version 1.7 remains in the cache.
