### ISSUE TITLE
Bankwire validation error when client confirms order

### ISSUE THREAD

**Issue by wa05** [PrestaShop/community-theme-16#273]
Hi Im receiving a an error about bankwire validation in my site http://papelerabarchiesi.com.ar

The request status of  http://papelerabarchiesi.com.ar/store/module/bankwire/validation is 302 
**302 Moved Temporarily** when I'm confirming an order 

The order went correctly to the state that it needs to be.. (a new state created by me: PENDING FOR REVISION), but Im still receiving the error..

any clue about this ?

**Comment by kpodemski** [comment]
Hello,

do you have any issues while doing same thing on default theme? we don't really do anything special with bankwire module, it seems that your issue is not theme related

**Comment by wa05** [comment]
Thanks for the answer, I'll go back with the changes in the order state maybe that's the problem
