### ISSUE TITLE
Remove HTML comments, use block IDs to identify module blocks

### ISSUE THREAD

**Issue by gskema** [PrestaShop/community-theme-16#40]
HTML comments = wasted bandwidth;
They're supposedly useful for developers to identify blocks, but blocks should be identified by their IDs;
Also HTML comments look like poor in Inspector view :laughing:

**Comment by kpodemski** [comment]
Well, I don't agree with this :) For me it is must have to do something like this:

```
<div class="some-block">

</div><!-- .some-block -->
```

it helps a lot :) if you're writing about some fancy comments like  - i'm ok with deleting these

**Comment by gskema** [comment]
Sure, but see if we can remove some or even change them with smarty comment `{* .some-block *}`.

**Comment by kpodemski** [comment]
I remember that sometimes it was useful to have comment ending module block and to be honest I didn't see this as something wrong, also, if you have HTML optimization enabled in Performance tab comments are deleted.
