### ISSUE TITLE
All images inside .rte receive .img-responsive

### ISSUE THREAD

**Issue by gskema** [PrestaShop/community-theme-16#44]
At `global.js`: `$('.rte img').addClass('img-responsive')`. This would force images to stay inside the container and not overflow.

**Comment by kpodemski** [comment]
:+1: 

common problem on my support, I always forgot about this!

**Comment by gskema** [comment]
Ok, then I'm moving this to `0.5.0`

**Comment by schibu83** [comment]
:+1: that´s a veeery good Idea :smile:

**Comment by gskema** [comment]
#159
