### ISSUE TITLE
Test page demonstrating component styles

### ISSUE THREAD

**Issue by gskema** [PrestaShop/community-theme-16#55]
Something like https://bootswatch.com/cosmo/, where you could view everything at once

**Comment by kpodemski** [comment]
:+1:

**Comment by true0r** [comment]
:+1:

**Comment by gskema** [comment]
Most likely it will be a module, since it's impossible to pull in all the assets and modifications into a static page. We could also add some developers extras to that module, I don't know which yet :D

**Comment by gskema** [comment]
#127
