### ISSUE TITLE
Product page image zoom

### ISSUE THREAD

**Issue by gskema** [PrestaShop/community-theme-16#57]
This may be a nice alternative:

http://imgix.github.io/drift/

**Comment by kpodemski** [comment]
:+1:

**Comment by gskema** [comment]
~~I tested it on mobile, doesnt seem to work very well :/~~ We should test it again in the future.

**Comment by kpodemski** [comment]
Well, I always turn off jqZoom on mobile, it is useless IMO, never search for anything in replace with friendly-mobile tho...

**Comment by gskema** [comment]
#162
