### ISSUE TITLE
Refactor picture thumb carousel in product page

### ISSUE THREAD

**Issue by gskema** [PrestaShop/community-theme-16#63]
Refactor into `thumbnail`s places in `.col-*`

**Comment by kpodemski** [comment]
This is not a good idea, use fixed width for images here, you'll have tons of problems using percentage width and `.col-*`

**Comment by gskema** [comment]
#62 and #63 it's a huge mess in JS, CSS and HTML, almost a slider built from scratch. My idea was to just add simple image bloks like: http://i.imgur.com/uQnrHkI.png , but maybe adding a slider would be a better idea if there were more than 6 images.

**Comment by kpodemski** [comment]
Well, maybe it is good to not have build-in carousel (let developer decide! :)) but I'm against using `.col-*`, as I said, percentage width it is always a problem while using owlCarousel and few other scripts

**Comment by schibu83** [comment]
I would prefer to remove the thumbsslider, show max. 3 thumbs under the big image and integrate something like a "show more" chevron or plus if there are more pictures. Or is this to far away from the original?

**Comment by gskema** [comment]
#162
