### ISSUE TITLE
[*] FO: Clean up icon elements

### ISSUE THREAD

**Issue by gskema** [PrestaShop/community-theme-16#79]
Remove classes `.left` `.right`.
Add `.icon` class to all icons

**Comment by kpodemski** [comment]
Why you'd like to remove these classes? It is sometimes ok to have left or right, especially for checkout buttons where we have possibility to control margins? any alternative?

**Comment by gskema** [comment]
I removed the compat styles temporarily but we will bring them back. The correct way to add a space between the icon and text is to add it in HTML `<i ...></i> Text`. The previous styles added 5px left margin by default and set it to 0 when icon had .right class. This was verry poor practice imo.

**Comment by kpodemski** [comment]
Ok but if we have:
`<i ...></i> text` (eg. back to shopping) - `i` should have margin from right
`text <i ...></i>` (eg. proceed checkout) - `i` should have margin from left

how you'll control and target these specific cases?

**Comment by gskema** [comment]
These spaces are already fixed in the community theme, for campat styles we can try to utilize .right and .left classes from legacy markup

**Comment by gskema** [comment]
https://github.com/PrestaShop/community-theme-16/pull/81, #83, #82
