### ISSUE TITLE
Nicer alert/error messages

### ISSUE THREAD

**Issue by gskema** [PrestaShop/community-theme-16#87]
https://github.com/lipis/bootstrap-sweetalert

**Comment by eschiendorfer** [comment]
http://t4t5.github.io/sweetalert/

I saw this here... This is probably same project. It looks amazing!

**Comment by gskema** [comment]
Yes, this is the same (you can see that the one I linked is **forked** from this). I don't know which would be better to use :)

**Comment by firstred** [comment]
The fork is no longer maintained?

Looks like a good idea. I'm in favor of http://t4t5.github.io/sweetalert/

**Comment by gskema** [comment]
You can now easily replace fancybox error popus with 3rd party plugin:

https://github.com/PrestaShop/community-theme-16/pull/202

Just add your library file to autoload js/css and customize `PrestaShop.showError()` function.
