### ISSUE TITLE
Incorrect config file

### ISSUE THREAD

**Issue by KloonDuino** [PrestaShop/community-theme-16#9]
There seem to be some problems when I zip up the files and try to import the theme in PS 1.6.1.3
The importer is complaining about a config file, and when I compare the config file to another config.xml (that does work) there seem to be a lot of things missing.......

**Comment by gskema** [comment]
Hello,

indeed the `config.xml` file is missing, thanks for poiting that out. We'll add it soon. Sorry for the trouble.

**Comment by KloonDuino** [comment]
No problem. Keep up the good work :)

**Comment by gskema** [comment]
Hello,

the folder structure has been updated and `Config.xml` has been added. `.css` files and not included in the repository, you have to compile them using `compass` or download the `v0.1.0-community-theme-16.zip` archive under the **Releases** tab (coming soon).
